/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'id' : string,
  'subject' : string,
  'handled' : boolean,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'category' : string,
}
export interface DropOffRecord {
  'customerName' : string,
  'verified' : boolean,
  'contactInfo' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
  'photo' : [] | [ExternalBlob],
  'reservationId' : string,
}
export type ExternalBlob = Uint8Array;
export interface PickupStatus {
  'paymentStatus' : string,
  'timestamp' : bigint,
  'pickupConfirmed' : boolean,
  'reservationId' : string,
}
export interface Reservation {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'contactInfo' : string,
  'date' : string,
  'createdAt' : bigint,
  'notes' : string,
  'assignedStaff' : [] | [Principal],
  'timeSlot' : string,
}
export interface ServicePricing {
  'premium' : bigint,
  'volumeDiscounts' : Array<[bigint, bigint]>,
  'specialty' : bigint,
  'addOns' : Array<[string, bigint]>,
  'standard' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDropOffRecord' : ActorMethod<[DropOffRecord], undefined>,
  'createReservation' : ActorMethod<[Reservation], undefined>,
  'getAllContactForms' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllDropOffRecords' : ActorMethod<[], Array<DropOffRecord>>,
  'getAllPickupStatuses' : ActorMethod<[], Array<PickupStatus>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDropOffRecord' : ActorMethod<[string], [] | [DropOffRecord]>,
  'getPickupStatus' : ActorMethod<[string], [] | [PickupStatus]>,
  'getReservation' : ActorMethod<[string], [] | [Reservation]>,
  'getServicePricing' : ActorMethod<[], [] | [ServicePricing]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerStaff' : ActorMethod<[], boolean>,
  'markContactFormHandled' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[ContactFormSubmission], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePickupStatus' : ActorMethod<[PickupStatus], undefined>,
  'updateReservationStatus' : ActorMethod<[string, string, string], undefined>,
  'updateServicePricing' : ActorMethod<[ServicePricing], undefined>,
  'verifyDropOff' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];