/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DropOffRecord = IDL.Record({
  'customerName' : IDL.Text,
  'verified' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'reservationId' : IDL.Text,
});
export const Reservation = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'contactInfo' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'assignedStaff' : IDL.Opt(IDL.Principal),
  'timeSlot' : IDL.Text,
});
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'handled' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const PickupStatus = IDL.Record({
  'paymentStatus' : IDL.Text,
  'timestamp' : IDL.Int,
  'pickupConfirmed' : IDL.Bool,
  'reservationId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ServicePricing = IDL.Record({
  'premium' : IDL.Nat,
  'volumeDiscounts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'specialty' : IDL.Nat,
  'addOns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'standard' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDropOffRecord' : IDL.Func([DropOffRecord], [], []),
  'createReservation' : IDL.Func([Reservation], [], []),
  'getAllContactForms' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllDropOffRecords' : IDL.Func([], [IDL.Vec(DropOffRecord)], ['query']),
  'getAllPickupStatuses' : IDL.Func([], [IDL.Vec(PickupStatus)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDropOffRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DropOffRecord)],
      ['query'],
    ),
  'getPickupStatus' : IDL.Func([IDL.Text], [IDL.Opt(PickupStatus)], ['query']),
  'getReservation' : IDL.Func([IDL.Text], [IDL.Opt(Reservation)], ['query']),
  'getServicePricing' : IDL.Func([], [IDL.Opt(ServicePricing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerStaff' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactFormHandled' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePickupStatus' : IDL.Func([PickupStatus], [], []),
  'updateReservationStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateServicePricing' : IDL.Func([ServicePricing], [], []),
  'verifyDropOff' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DropOffRecord = IDL.Record({
    'customerName' : IDL.Text,
    'verified' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'reservationId' : IDL.Text,
  });
  const Reservation = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'contactInfo' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'assignedStaff' : IDL.Opt(IDL.Principal),
    'timeSlot' : IDL.Text,
  });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'handled' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const PickupStatus = IDL.Record({
    'paymentStatus' : IDL.Text,
    'timestamp' : IDL.Int,
    'pickupConfirmed' : IDL.Bool,
    'reservationId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ServicePricing = IDL.Record({
    'premium' : IDL.Nat,
    'volumeDiscounts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'specialty' : IDL.Nat,
    'addOns' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'standard' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDropOffRecord' : IDL.Func([DropOffRecord], [], []),
    'createReservation' : IDL.Func([Reservation], [], []),
    'getAllContactForms' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllDropOffRecords' : IDL.Func([], [IDL.Vec(DropOffRecord)], ['query']),
    'getAllPickupStatuses' : IDL.Func([], [IDL.Vec(PickupStatus)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDropOffRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DropOffRecord)],
        ['query'],
      ),
    'getPickupStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PickupStatus)],
        ['query'],
      ),
    'getReservation' : IDL.Func([IDL.Text], [IDL.Opt(Reservation)], ['query']),
    'getServicePricing' : IDL.Func([], [IDL.Opt(ServicePricing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerStaff' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactFormHandled' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePickupStatus' : IDL.Func([PickupStatus], [], []),
    'updateReservationStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateServicePricing' : IDL.Func([ServicePricing], [], []),
    'verifyDropOff' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };